name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
      
  Android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        cd VideoShell.Android
        msbuild VideoShell.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
        
  uwp:
    runs-on:ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: UWP
      run: |
        cd ..
        nuget restore
        msbuild VideoShell.UWP/VideoShell.UWP.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
