name: CI on Push and Pull Request

on: [push, pull_request]

jobs:
      
  sln:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: SLN
      run: |
        nuget restore
        msbuild VideoShell.sln /verbosity:normal /t:Rebuild /p:Configuration=Debug
